version: '3.5'

services:
  eventstore:
    container_name: KajSpike-eventstore
    image: eventstore/eventstore
    ports:
        - 2113:2113
        - 1113:1113
    environment:
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
  kajspike:
    container_name: KajSpike-App
    image: kajspike
    ports:
      - 8085:80
      - 8086:443
    deploy:
      replicas: 2

